# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
# END_KITTY_FONTS

shell zsh

# splits layout is required for --location=hsplit/vsplit to take effect
enabled_layouts splits:split_axis=horizontal,stack

# Window splits
map f5 launch --cwd=current --location=hsplit
map f6 launch --cwd=current --location=vsplit
map f4 launch --cwd=current --location=split
map f7 layout_action rotate

# Move the active window
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

# Switch focus to neighboring window
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME
